apiVersion: v1
kind: Namespace
metadata:
  name: adapter
---
apiVersion: v1
kind: Pod
metadata:
  name: adapter
  namespace: adapter
  labels:
    type: ambassador
spec:
  containers:
  - name: adapter-service
    image: adapter-service
---
apiVersion: v1
kind: Service
metadata:
  name: adapter-service
  namespace: adapter
spec:
  selector:
    matchLabels:
      type: ambassador
  ports:
    - protocol: TCP
      port: 61
      targetPort: 60
 
