apiVersion: v1
kind: Namespace
metadata:
  name: kdsn00101
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-kdsn00101
  namespace: kdsn00101
  labels:
    app: kdsn
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kdsn
  template:
    metadata:
      labels:
        app: kdsn
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
