apiVersion: v1
kind: Namespace
metadata:
  name: app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: maxSurge
spec:
  replicas: 3
  selector:
    matchLabels:
      app: maxSurge
  template:
    metadata:
      labels:
        app: maxSurge
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
